config/routes.rb
Rails.application.routes.draw do
  match '/404', via: :all, to:  'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'
  resources :bookings
  devise_for :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :client do
    authenticated :client do
      root 'clientdashboards#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
    # for logout
    get '/clients/sign_out', to: 'devise/sessions#destroy'
  end

  get 'clients/edit', to: 'clients#edit'
  
  get 'admin', to: 'admin#index'
  get 'admin/clients', to: 'admin#clients'
  get 'admin/profile', to: 'admin#profile'
  get 'admin/settings', to: 'admin#settings'
  get 'admin/pic', to: 'admin#pic'
  delete "admin/delete_client", to: "admin#delete_client", as: :delete_client
  delete "purge_profile_picture", to: "admin#purge_profile_picture"

  get 'set_theme', to: 'admin#update_theme'

  post 'admin/settings/verifier', to: 'adminpasswords#verifier', as: :verifier_adminpassword
  get 'admin/settings/verify', to: 'adminpasswords#verify', as: :verify_adminpassword
  get "admin/password", to: "adminpasswords#edit", as: :edit_adminpassword
  patch "admin/password", to: "adminpasswords#update"

  get "clientdashboard", to: "clientdashboards#index"
  get "clientdashboard/tomorrow", to: "clientdashboards#tomorrow_bookings"
  get "clientdashboard/upcoming", to: "clientdashboards#upcoming_bookings"
  get "clientdashboard/time_slots", to: "clientdashboards#time_slots"
  get "clientdashboard/accept_booking", to: "clientdashboards#accept_booking", as: :accept_booking
  get "clientdashboard/decline_booking", to: "clientdashboards#decline_booking", as: :decline_booking

  get "timeslots", to: "timeslots#index"
  get "timeslots/delete", to: "timeslots#delete"
  get '/timeslots/date', to: 'timeslots#take_date', as: 'timeslots_date'
  get '/timeslots/time', to: 'timeslots#take_time', as: 'timeslots_time'

  get 'single_day', to: 'bookings#single_day'
  get 'newww_booking', to: 'bookings#new'

  get 'book/:clientid', to: "bookings#index", as: 'book_client'
end

app/views/admin/clients.html.erb
<%= turbo_frame_tag "admin" do %>
  <%= render partial: "shared/notice" %>
  <%= render partial: "shared/alert" %>
  <header>Client List</header>
  <main class="admin--main">
    <article>
      <div class="admin--new-clients" style="min-height:80vh;">
        <div class="admin--client-search">
          <%= search_form_for @q, url: :admin_clients, data: {turbo_frame: :results} do |f| %>
            <%= f.search_field :name_or_contact_no_or_email_cont, oninput: 'this.form.requestSubmit()', autocomplete: 'off', placeholder: "Search" %>
          <% end %>
        </div>

        <%= turbo_frame_tag :results do %>
          <div class="admin--pagination">
            <%== pagy_nav(@pagy) %>
          </div>
          <table>
            <tr>
              <th>S.N</th>
              <th>Name</th>
              <th>Created On</th>
              <th>ID</th>
              <th>Contact</th>
              <th>Email</th>
              <th>Location</th>
              <th>Photo</th>
            </tr>
            <% sn = 1 %>
            <% @client_list.each do |client| %>
              <tr>
                <td><%= sn %></td>
                <td><%= client.name %></td>
                <td><%= client.created_at.strftime('%Y/%m/%d') %></td>
                <td><%= client.id %></td>
                <td><%= client.contact_no %></td>
                <td><%= client.email %></td>
                <td><%= client.location %></td>
                <td><%= link_to "View", admin_pic_path(id: client.id), data: {turbo_frame: "modal"} %></td>
                <td><% unless client.id == current_client.id %><%=link_to "Delete", delete_client_path(id: client.id), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %><% end %></td>
              </tr>
            <% sn+=1 %>
            <% end %>
          </table>
          <% end %>
        </div>
      </article>
  </main>
  <%= turbo_frame_tag "modal" %>
<% end %>

app/views/admin/index.html.erb
<div class="admin-section <%= cookies[:theme] %>">
  <%= render partial: "shared/navbar" %>

  <div class="admin--body">
    <%= turbo_frame_tag "admin" do %>
      <%= render partial: "shared/notice" %>
      <%= render partial: "shared/alert" %>

      <header style="background-color:unset;">
        Hello <%= current_client.name %>!
        <div class="copy-url tooltip">
          <%= text_field_tag 'urlField', @url, style:"display: none;" %>
          <%= link_to "javascript:urlCopy()" do %>
            <i class='bx bx-copy-alt'></i>
          <% end %>
          <span class="tooltiptext">Copy to clipboard</span>
        </div>
      </header>
      <main class="admin--main">
        <article style="display:flex; flex-direction: column;">
          <div class="admin--new-clients" style="max-height: 45vh; overflow:hidden;">
            <h1>New Clients</h1>
            <table>
              <tr>
                <th>S.N</th>
                <th>Name</th>
                <th>Created On</th>
                <th>ID</th>
              </tr>
              <% sn = 1 %>
              <% @clients.each do |client| %>
                <tr>
                  <td><%= sn %></td>
                  <td><%= client.name %></td>
                  <td><%= client.created_at.strftime('%Y/%m/%d') %></td>
                  <td><%= client.id %></td>
                </tr>
                <% sn+=1 %>
              <% end %>
            </table>
          </div>
          <div class="admin--count">
            <%= image_tag "count" %>
            <h4>Total Clients</h4>
            <div style="background-color:white; font-weight:bold; padding: 20px; border-radius: 20px; margin-top:20px; width: 130px"><%= @total_clients %></div>
          </div>
        </article>
        <aside>
          <div class="admin--new-clients" style="height: 80vh;">
            <h1>Today's Appointments</h1>
            <table>
              <tr>
                <th>S.N</th>
                <th>Time</th>
                <th>From</th>
                <th>To</th>
              </tr>
              <% sn = 1 %>
              <% @todays.each do |today| %>
                <tr>
                  <td><%= sn %></td>
                  <td><%= today.start_time.strftime('%k:%M') %> to <%= (today.start_time+30.minutes).strftime('%k:%M') %> </td>
                  <td><%= today.bookings.first.user_name %></td>
                  <td><%= today.client.name %></td>
                </tr>
                <% sn+=1 %>
              <% end %>
            </table>
          </div>
        </aside>
      </main>
    <% end %>
  </div>
</div>

app/views/admin/pic.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal-pic">
    <% if @client.profile_picture.attached? %>
      <%= image_tag @client.profile_picture %>
    <% else %>
      No Profile Picture
    <% end %>
    <%= link_to "Close", admin_clients_path, data: { controller: "modals", action: "modals#close" }, class: "cancel-button" %>
  </div>
<% end %>

app/views/admin/settings.html.erb
<%= turbo_frame_tag "admin" do %>
  <header>Settings</header>
    <main class="admin--main">
      <article>
        <div class="admin--settings">
          <%= link_to "Change Password", verify_adminpassword_path %><br>
          <% if current_client.is_admin %>
            <% if cookies[:theme] == "dark" %>
              <%= link_to "Light Mode", set_theme_path(theme: 'light') %>
            <% else %>
              <%= link_to "Dark Mode", set_theme_path(theme: 'dark') %>
            <% end %>
          <% end %>
        </div>
      </article>
    </main>
<% end %>