config/routes.rb
Rails.application.routes.draw do
  match '/404', via: :all, to:  'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'
  resources :bookings
  devise_for :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :client do
    authenticated :client do
      root 'clientdashboards#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
    # for logout
    get '/clients/sign_out', to: 'devise/sessions#destroy'
  end

  get 'clients/edit', to: 'clients#edit'
  
  get 'admin', to: 'admin#index'
  get 'admin/clients', to: 'admin#clients'
  get 'admin/profile', to: 'admin#profile'
  get 'admin/settings', to: 'admin#settings'
  get 'admin/pic', to: 'admin#pic'
  delete "admin/delete_client", to: "admin#delete_client", as: :delete_client
  delete "purge_profile_picture", to: "admin#purge_profile_picture"

  get 'set_theme', to: 'admin#update_theme'

  post 'admin/settings/verifier', to: 'adminpasswords#verifier', as: :verifier_adminpassword
  get 'admin/settings/verify', to: 'adminpasswords#verify', as: :verify_adminpassword
  get "admin/password", to: "adminpasswords#edit", as: :edit_adminpassword
  patch "admin/password", to: "adminpasswords#update"

  get "clientdashboard", to: "clientdashboards#index"
  get "clientdashboard/tomorrow", to: "clientdashboards#tomorrow_bookings"
  get "clientdashboard/upcoming", to: "clientdashboards#upcoming_bookings"
  get "clientdashboard/time_slots", to: "clientdashboards#time_slots"
  get "clientdashboard/accept_booking", to: "clientdashboards#accept_booking", as: :accept_booking
  get "clientdashboard/decline_booking", to: "clientdashboards#decline_booking", as: :decline_booking

  get "timeslots", to: "timeslots#index"
  get "timeslots/delete", to: "timeslots#delete"
  get '/timeslots/date', to: 'timeslots#take_date', as: 'timeslots_date'
  get '/timeslots/time', to: 'timeslots#take_time', as: 'timeslots_time'

  get 'single_day', to: 'bookings#single_day'
  get 'newww_booking', to: 'bookings#new'

  get 'book/:clientid', to: "bookings#index", as: 'book_client'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :timeslot
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    begin
      @client = Client.find(params[:clientid])
      @timeslots = Timeslot.where(
        start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week,
        client_id: @client.id, is_confirm: false)
    rescue
      redirect_to '/404'
    end
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  def single_day
    @date = params[:date]
    @date2 = @date.to_time
    @client_id = params[:client_id]
    @timeslots = Timeslot.where(date: @date, client_id: @client_id, is_confirm: false)
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @timeslot = Timeslot.find(params[:id])
    @client = Client.find(params[:client_id])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        @timeslot = Timeslot.find(@booking.timeslot_id)
        @client = Client.find(@timeslot.client_id)
        BookingMailer.booking_confirm(@booking, @timeslot, @client).deliver_later
        format.html { redirect_to booking_url(@booking) }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:user_name, :user_email, :user_contact, :description, :timeslot_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>User name:</strong>
    <%= booking.user_name %>
  </p>

  <p>
    <strong>User email:</strong>
    <%= booking.user_email %>
  </p>

  <p>
    <strong>User contact:</strong>
    <%= booking.user_contact %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= booking.description %>
  </p>

  <p>
    <strong>Timeslot:</strong>
    <%= booking.timeslot_id %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_name, "Name" %>
    <%= form.text_field :user_name, required: true %>
  </div>

  <div>
    <%= form.label :user_email, "Email" %>
    <%= form.email_field :user_email, required: true %>
  </div>

  <div>
    <%= form.label :user_contact, "Contact No." %>
    <%= form.text_field :user_contact, required: true %>
  </div>

  <div>
    <%= form.label :description, "What would you like to discuss?" %>
    <%= form.text_area :description, required: true %>
  </div>

  <div>
    <%= form.hidden_field :timeslot_id, value: @timeslot.id %>
  </div>

  <div style="display:flex;">
    <div class="booking-back">
      <%= link_to "Back", book_client_path(@client.id), data: { turbo_frame: "_top" } %>
    </div>
    <div class="booking-submit">
      <%= form.submit "Book" %>
    </div>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<div class="user-section">
  <div class="user-sidebar">
    <div class="admin--navbar-pic">
      <% if @client.profile_picture.attached? %>
        <%= image_tag @client.profile_picture %>
      <% else %>
        <i class='bx bx-user-circle' ></i>
      <% end %>
    </div>
    <h2><%= @client.name %></h2>
    <h4><%= @client.profession %></h4>
  </div>
  <div class="user-main">
    <%= turbo_frame_tag "calendar" do %>
      <div class="user-main-body">
        <div class="user-calendar">
          <div class="user-calendar-header">
            Select a date & time
          </div>
          <div class="user-calendar-body">
            <%= month_calendar(events: @timeslots) do |date, timeslots| %>
              <%= link_to date.day, single_day_path(date: date, client_id: @client.id), data: { turbo_frame: "timeslots" } %>
            <% end %>
          </div>
        </div>
        <div class="user-timeslot">
          <%= turbo_frame_tag "timeslots" do %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="booking-details">
  <div class="booking-sidebar">
      <h2>30 mins meeting with <%= @client.name %></h2>
      <h4><i class='bx bx-time'></i><%= @timeslot.start_time.strftime('%k:%M') %> - <%= (@timeslot.start_time+30.minutes).strftime('%k:%M') %></h4>
      <h4><i class='bx bx-calendar'></i> <%= @timeslot.date.to_time.strftime("%a, %b %d %Y") %></h4>
      <h4><i class='bx bx-globe'></i> Nepal Time</h4>
    </div>
  <div class="user-booking" style="flex:4;">
    <%= turbo_frame_tag "calendar" do %>
      <h1>Enter Details</h1>
      <%= render "form", booking: @booking %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<%= turbo_frame_tag "calendar" do %>
  <div class="booking-confirm">
    <%= image_tag "booking_confirm" %>
    <h1>Congratulations!</h1>
    <h4>Your appointment has been successfully requested.</h4>
  </div>
<% end %>

app/views/bookings/single_day.html.erb
<%= turbo_frame_tag "timeslots" do %>
  <div class="user-timeslot-page">
    <div class="user-timeslot-header">
      <%= @date2.strftime("%a, %b %d, %Y") %>
    </div>
    <div class="user-timeslot-body">
      <% @timeslots.each do |timeslot| %>
        <div class="user-time-slot">
          <%= link_to newww_booking_path(id: timeslot.id, client_id: @client_id), data: { turbo_frame: "_top" } do %>
            <%= timeslot.start_time.strftime('%l:%M %p') %> - <%= (timeslot.start_time+30.minutes).strftime('%l:%M %p') %>
          <% end %>
        </div>    
      <% end %>
    </div>
  </div>
<% end %>