config/routes.rb
Rails.application.routes.draw do
  match '/404', via: :all, to:  'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'
  resources :bookings
  devise_for :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :client do
    authenticated :client do
      root 'clientdashboards#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
    # for logout
    get '/clients/sign_out', to: 'devise/sessions#destroy'
  end

  get 'clients/edit', to: 'clients#edit'
  
  get 'admin', to: 'admin#index'
  get 'admin/clients', to: 'admin#clients'
  get 'admin/profile', to: 'admin#profile'
  get 'admin/settings', to: 'admin#settings'
  get 'admin/pic', to: 'admin#pic'
  delete "admin/delete_client", to: "admin#delete_client", as: :delete_client
  delete "purge_profile_picture", to: "admin#purge_profile_picture"

  get 'set_theme', to: 'admin#update_theme'

  post 'admin/settings/verifier', to: 'adminpasswords#verifier', as: :verifier_adminpassword
  get 'admin/settings/verify', to: 'adminpasswords#verify', as: :verify_adminpassword
  get "admin/password", to: "adminpasswords#edit", as: :edit_adminpassword
  patch "admin/password", to: "adminpasswords#update"

  get "clientdashboard", to: "clientdashboards#index"
  get "clientdashboard/tomorrow", to: "clientdashboards#tomorrow_bookings"
  get "clientdashboard/upcoming", to: "clientdashboards#upcoming_bookings"
  get "clientdashboard/time_slots", to: "clientdashboards#time_slots"
  get "clientdashboard/accept_booking", to: "clientdashboards#accept_booking", as: :accept_booking
  get "clientdashboard/decline_booking", to: "clientdashboards#decline_booking", as: :decline_booking

  get "timeslots", to: "timeslots#index"
  get "timeslots/delete", to: "timeslots#delete"
  get '/timeslots/date', to: 'timeslots#take_date', as: 'timeslots_date'
  get '/timeslots/time', to: 'timeslots#take_time', as: 'timeslots_time'

  get 'single_day', to: 'bookings#single_day'
  get 'newww_booking', to: 'bookings#new'

  get 'book/:clientid', to: "bookings#index", as: 'book_client'
end

app/views/shared/_alert.html.erb
<% if alert %>
  <div class="notice-alert">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_clientnav.html.erb
<nav class="admin--navbar">
  <div class="admin--navbar-pic">
    <% if current_client.profile_picture.attached? %>
      <%= image_tag current_client.profile_picture %>
    <% else %>
      <i class='bx bx-user-circle' ></i>
    <% end %>
  </div>
  <ul class="admin--navbar-list">
    <%= link_to clientdashboard_path do %>
      <li><i class='bx bx-grid-alt'></i>Dashboard</li>
    <% end %>
    <%= link_to admin_profile_path, data: { turbo_frame: "admin" } do %>
      <li><i class='bx bx-message-alt-edit'></i>Profile</li>
    <% end %>
    <%= link_to timeslots_path, data: { turbo_frame: "admin" } do %>
      <li><i class='bx bx-group' ></i>Timeslots</li>
    <% end %>
    <%= link_to admin_settings_path, data: { turbo_frame: "admin" } do %>
      <li><i class='bx bx-cog' ></i>Settings</li>
    <% end %>
    <%= link_to destroy_client_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to Log Out?' } do %>
      <li><i class='bx bx-log-out' ></i>Logout</li>
    <% end %>
  </ul>
</nav>

app/views/shared/_navbar.html.erb
<nav class="admin--navbar">
  <div class="admin--navbar-pic">
    <% if current_client.profile_picture.attached? %>
      <%= image_tag current_client.profile_picture %>
    <% else %>
      <i class='bx bx-user-circle' ></i>
    <% end %>
  </div>
  <ul class="admin--navbar-list">
    <%= link_to admin_path, data: { turbo_frame: "admin" } do %>
      <li><i class='bx bx-grid-alt'></i>Dashboard</li>
    <% end %>
    <%= link_to admin_profile_path, data: { turbo_frame: "admin" } do %>
      <li><i class='bx bx-message-alt-edit'></i>Profile</li>
    <% end %>
    <%= link_to admin_clients_path, data: { turbo_frame: "admin" } do %>
      <li><i class='bx bx-group' ></i>Clients</li>
    <% end %>
    <%= link_to admin_settings_path, data: { turbo_frame: "admin" } do %>
      <li><i class='bx bx-cog' ></i>Settings</li>
    <% end %>
    <%= link_to destroy_client_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to Log Out?' } do %>
      <li><i class='bx bx-log-out' ></i>Logout</li>
    <% end %>
  </ul>
</nav>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="notice-alert">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <%= notice %>
  </div>
<% end %>