config/routes.rb
Rails.application.routes.draw do
  match '/404', via: :all, to:  'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'
  resources :bookings
  devise_for :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :client do
    authenticated :client do
      root 'clientdashboards#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
    # for logout
    get '/clients/sign_out', to: 'devise/sessions#destroy'
  end

  get 'clients/edit', to: 'clients#edit'
  
  get 'admin', to: 'admin#index'
  get 'admin/clients', to: 'admin#clients'
  get 'admin/profile', to: 'admin#profile'
  get 'admin/settings', to: 'admin#settings'
  get 'admin/pic', to: 'admin#pic'
  delete "admin/delete_client", to: "admin#delete_client", as: :delete_client
  delete "purge_profile_picture", to: "admin#purge_profile_picture"

  get 'set_theme', to: 'admin#update_theme'

  post 'admin/settings/verifier', to: 'adminpasswords#verifier', as: :verifier_adminpassword
  get 'admin/settings/verify', to: 'adminpasswords#verify', as: :verify_adminpassword
  get "admin/password", to: "adminpasswords#edit", as: :edit_adminpassword
  patch "admin/password", to: "adminpasswords#update"

  get "clientdashboard", to: "clientdashboards#index"
  get "clientdashboard/tomorrow", to: "clientdashboards#tomorrow_bookings"
  get "clientdashboard/upcoming", to: "clientdashboards#upcoming_bookings"
  get "clientdashboard/time_slots", to: "clientdashboards#time_slots"
  get "clientdashboard/accept_booking", to: "clientdashboards#accept_booking", as: :accept_booking
  get "clientdashboard/decline_booking", to: "clientdashboards#decline_booking", as: :decline_booking

  get "timeslots", to: "timeslots#index"
  get "timeslots/delete", to: "timeslots#delete"
  get '/timeslots/date', to: 'timeslots#take_date', as: 'timeslots_date'
  get '/timeslots/time', to: 'timeslots#take_time', as: 'timeslots_time'

  get 'single_day', to: 'bookings#single_day'
  get 'newww_booking', to: 'bookings#new'

  get 'book/:clientid', to: "bookings#index", as: 'book_client'
end

app/controllers/clientdashboards_controller.rb
class ClientdashboardsController < ApplicationController
    before_action :check_admin, only: [:index]
    
    def index
      @bookings = Booking.where(is_accepted: false).where(:timeslots => {:client_id => current_client.id}).joins(:timeslot)
      @accepted_bookings = Booking.where(is_accepted: true).where(:timeslots => {:client_id => current_client.id}).joins(:timeslot)
      @today_bookings = @accepted_bookings.where(:timeslots => {:date => Date.today})
      @url = request.base_url + book_client_path(clientid: current_client.id.to_s)
    end

    def tomorrow_bookings
      @accepted_bookings = Booking.where(is_accepted: true).where(:timeslots => {:client_id => current_client.id}).joins(:timeslot)
      @tomorrow_bookings = @accepted_bookings.where(:timeslots => {:date => Date.tomorrow})
    end

    def upcoming_bookings
      @accepted_bookings = Booking.where(is_accepted: true).where(:timeslots => {:client_id => current_client.id}).joins(:timeslot)
      @upcoming_bookings = @accepted_bookings.where(:timeslots => {:date => 2.days.from_now..})
    end

    def accept_booking
      @booking = Booking.find(params[:id])
      @booking.is_accepted = true
      @booking.save
      @timeslot = Timeslot.find(@booking.timeslot_id)
      @timeslot.is_confirm = true
      @timeslot.booking_id = @booking.id
      @timeslot.save
      BookingMailer.booking_accept(@booking).deliver_later
      redirect_to clientdashboard_path, notice: "Booking accepted."
    end

    def decline_booking
      @booking = Booking.find(params[:id])
      BookingMailer.booking_decline(@booking).deliver_now
      @booking.destroy
      redirect_to clientdashboard_path, notice: "Booking declined."
    end

    def time_slots
    end

    def check_admin
      redirect_to admin_path if current_client.present? && current_client.is_admin
    end
end

app/views/clientdashboards/index.html.erb
<div class="admin-section">
  <%= render partial: "shared/clientnav" %>
  <div class="admin--body">
    <%= turbo_frame_tag "admin" do %>
      <%= render partial: "shared/notice" %>
      <%= render partial: "shared/alert" %>
      <header style="background-color:unset;">
        Hello <%= current_client.name %>!
        <div class="copy-url tooltip">
          <%= text_field_tag 'urlField', @url, style:"display: none;" %>
          <%= link_to "javascript:urlCopy()" do %>
            <i class='bx bx-copy-alt'></i>
          <% end %>
          <span class="tooltiptext" id="urlSpan">Copy to clipboard</span>
        </div>
      </header>
      <main class="admin--main">
        <article style="display:flex; flex-direction: column; flex: 3;">
          <div style="display:flex;">
            <div class="client-header"><%= link_to "Today", clientdashboard_path, data: { turbo_frame: "client" } %></div>
            <div class="client-header"><%= link_to "Tomorrow", clientdashboard_tomorrow_path, data: { turbo_frame: "client" } %></div>
            <div class="client-header"><%= link_to "Upcoming", clientdashboard_upcoming_path, data: { turbo_frame: "client" } %></div>
          </div>
          <div class="admin--new-clients todays">
            <%= turbo_frame_tag "client" do %>
              <table>
                <tr>
                  <th>S.N</th>
                  <th>Name</th>
                  <th>Date</th>
                  <th>Time</th>
                  <th>ID</th>
                  <th>Info</th>
                  <th>Status</th>
                </tr>
                <% sn = 1 %>
                <% @today_bookings.each do |booking| %>
                  <tr>
                    <td><%= sn %></td>
                    <td><%= booking.user_name %></td>
                    <td><%= booking.timeslot.date.strftime('%Y/%m/%d') %></td>
                    <td><%= booking.timeslot.start_time.strftime('%k:%M') %> - <%= (booking.timeslot.start_time+30.minutes).strftime('%k:%M') %></td>
                    <td><%= booking.id %></td>
                    <td class="link-icon"><%= link_to clientdashboard_path, data: { turbo_method: :get, turbo_confirm: booking.description } do %>
                      <i class='bx bx-file'></i><% end %></td>
                    <td><span class="client-request-confirm">Confirmed</span></td>
                  </tr>
                <% sn+=1 %>
                <% end %>
              </table>
            <% end %>
        </div>
        </article>
        <aside style="flex:2; display: flex; flex-direction: column;">
          <div class="client-header">Request</div>
          <div class="admin--new-clients">
            <% if @bookings.empty? %>
              <%= "No booking requests" %>
            <% else %>
              <table>
                <% @bookings.each do |booking| %>
                  <tr>
                    <td><%= booking.user_name %><br><span class="client-request-time"><%= booking.timeslot.start_time.strftime('%Y/%m/%d, %k:%M') %></span></td>
                    <td class="link-icon"><%= link_to clientdashboard_path, data: { turbo_method: :get, turbo_confirm: booking.description } do %>
                      <i class='bx bx-file'></i><% end %></td>
                    <td><%= link_to "Confirm", accept_booking_path(id: booking.id), class: 'client-request-confirm' %></td>
                    <td><%= link_to "Decline", decline_booking_path(id: booking.id), class: 'client-request-decline' %></td>
                  </tr>
                <% end %>
              </table>
            <% end %>
          </div>
        </aside>
      </main>
    <% end %>
  </div>
</div>

app/views/clientdashboards/tomorrow_bookings.html.erb
<%= turbo_frame_tag "client" do %>
  <table>
    <tr>
      <th>S.N</th>
      <th>Name</th>
      <th>Date</th>
      <th>Time</th>
      <th>ID</th>
      <th>Info</th>
      <th>Status</th>
    </tr>
    <% sn = 1 %>
    <% @tomorrow_bookings.each do |booking| %>
      <tr>
        <td><%= sn %></td>
        <td><%= booking.user_name %></td>
        <td><%= booking.timeslot.date.strftime('%Y/%m/%d') %></td>
        <td><%= booking.timeslot.start_time.strftime('%k:%M') %> - <%= (booking.timeslot.start_time+30.minutes).strftime('%k:%M') %></td>
        <td><%= booking.id %></td>
        <td class="link-icon"><%= link_to clientdashboard_path, data: { turbo_method: :get, turbo_confirm: booking.description } do %>
          <i class='bx bx-file'></i><% end %></td>
        <td><span class="client-request-confirm">Confirmed</span></td>
      </tr>
    <% sn+=1 %>
    <% end %>
  </table>
<% end %>

app/views/clientdashboards/upcoming_bookings.html.erb
<%= turbo_frame_tag "client" do %>
  <table>
    <tr>
      <th>S.N</th>
      <th>Name</th>
      <th>Date</th>
      <th>Time</th>
      <th>ID</th>
      <th>Info</th>
      <th>Status</th>
    </tr>
    <% sn = 1 %>
    <% @upcoming_bookings.each do |booking| %>
      <tr>
        <td><%= sn %></td>
        <td><%= booking.user_name %></td>
        <td><%= booking.timeslot.date.strftime('%Y/%m/%d') %></td>
        <td><%= booking.timeslot.start_time.strftime('%k:%M') %> - <%= (booking.timeslot.start_time+30.minutes).strftime('%k:%M') %></td>
        <td><%= booking.id %></td>
        <td class="link-icon"><%= link_to clientdashboard_path, data: { turbo_method: :get, turbo_confirm: booking.description } do %>
          <i class='bx bx-file'></i><% end %></td>
        <td><span class="client-request-confirm">Confirmed</span></td>
      </tr>
    <% sn+=1 %>
    <% end %>
  </table>
<% end %>